name: Github Pages CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'NasaChallenge2024/**'
      - '.github/workflows/gh-pages.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd NasaChallenge2024/JsSources && npm ci && cd ../..
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
    - run: dotnet publish ./NasaChallenge2024/
    - run: echo "* binary" >> NasaChallenge2024/bin/Release/net8.0/publish/wwwroot/.gitattributes
    - run: touch NasaChallenge2024/bin/Release/net8.0/publish/wwwroot/.nojekyll
    - run: sed -i 's+<base href="/" />+<base href="/NasaChallenge2024/" />+g' NasaChallenge2024/bin/Release/net8.0/publish/wwwroot/index.html
    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@releases/v3                             
      with:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages  
        FOLDER: NasaChallenge2024/bin/Release/net8.0/publish/wwwroot